apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-automation-prod-k8-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-automation-api-prod
  template:
    metadata:
      labels:
        app: devops-automation-api-prod
    spec:  
      containers:
      - name: devops-automation-api-prod
        image: asfahans/devops-automation
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: devops-automation-prod-k8-service
spec:
  selector:
    app: devops-automation-api-prod
  type: NodePort  
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
